---
- name: install apache
  hosts: all
  become: true
  tasks:
    - name: install webserver
      yum:
        name: httpd
        state: present
    - name: ensure service started
      service:
        name: httpd
        state: started
